CC = gcc
CFLAGS = -Wall -Wextra -Werror

all: findPhone add2PB

findPhone: findPhone.c
	$(CC) $(CFLAGS) -o findPhone findPhone.c

add2PB: add2PB.c
	$(CC) $(CFLAGS) -o add2PB add2PB.c

clean:
	rm -f program1 add2PB